version: "3.7"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    networks: 
      - processor-net
    depends_on:
      minio:
        condition: service_healthy

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-07-12T02-44-53Z
    networks:
      - processor-net
    environment:
      MINIO_ROOT_USER: migueleangel   # Cambia "tu_usuario" por el nombre de usuario que desees
      MINIO_ROOT_PASSWORD: fitnesvip1 # Cambia "tu_contraseña" por la contraseña que desees
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-volume:/data
    command: server --console-address ":9001"  /data
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  processor-net:
    driver: bridge

volumes:
  minio-volume: